"""add reasoning_metadata to messages

Revision ID: 38670e62f60e
Revises: 97036ea1a98e
Create Date: 2026-06-16 14:40:30.680756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38670e62f60e'
down_revision: Union[str, Sequence[str], None] = '97036ea1a98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reasoning_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reasoning_metadata')
    # ### end Alembic commands ###
