"""add_soft_delete_to_chat_sessions

Revision ID: 97036ea1a98e
Revises: 8caf265c1570
Create Date: 2026-06-11 21:28:07.941787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97036ea1a98e'
down_revision: Union[str, Sequence[str], None] = '8caf265c1570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_deleted')
    # ### end Alembic commands ###
