"""change embedding dimension to 3072

Revision ID: c45baff62420
Revises: 4e2183e77590
Create Date: 2026-07-12 00:08:00.389328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = 'c45baff62420'
down_revision: Union[str, Sequence[str], None] = '4e2183e77590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=VECTOR(dim=384),
               type_=VECTOR(dim=3072),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=VECTOR(dim=3072),
               type_=VECTOR(dim=384),
               existing_nullable=False)
    # ### end Alembic commands ###
